/* 성서 연구 서고 — 카탈로그 */
window.SITE_CATALOG = {site:{name:"성서 연구 서고",updated:"2026-08-01"},sections:[
{id:"bible",label:"성경읽기",original:"Biblia · Γραφή",script:"lat",studies:[{id:"reader",path:"bible/original.html",title:"성경읽기",original:"원어 · 개역개정",script:"lat",meta:"성경 66권 — 장·절 선택 · 구약 WLC/OSHB · 신약 NA28 · 개역개정 병렬 대조",desc:"성경책과 장절을 선택해 원문과 개역개정을 절 단위로 나란히 읽는다. 원어 단어에 마우스를 올리거나 터치하면 한글 스트롱 사전 풀이를 확인할 수 있다.",volumes:2}]},
{id:"lexicon",label:"원어 사전",original:"Λεξικόν · מִלּוֹן",script:"lat",studies:[{id:"strongs-lexicon",path:"lexicon/index.html",title:"히브리어·헬라어 스트롱 사전",original:"Ἑλληνικά · עִבְרִית",script:"lat",meta:"히브리어·아람어 H1–H8674 · 헬라어 실제 Strong 항목 5,523개 · 한글 원문 보존 · 번호·표제어·발음·뜻 검색 · 원어성경 호버 연결",desc:"사용자가 제공한 한글 스트롱 사전 자료를 구조화했다. 상세 페이지에서는 사전 원문을 확인하고, 성경읽기 화면에서는 원어 단어 위에서 간략 풀이를 바로 볼 수 있다.",volumes:6}]},
{id:"ot",label:"구약 연구",original:"תַּנַ\"ךְ",script:"heb",studies:[
{id:"genesis",path:"ot/genesis/index.html",title:"창세기 연구 서가",original:"בְּרֵאשִׁית",script:"heb",meta:"표준형 서가 — 성경읽기 50장 · 종합 개관 1편 · 장별 심층연구 21/50편 · 원어 연구 준비 중",desc:"우주의 시작에서 아브라함의 시험까지, 톨레도트 구조를 따라 1–20장과 22장을 심층연구로 제공한다. 여섯 주석을 기본 축으로 삼되 각 장에서 직접 확인한 자료 범위를 표시하며 나머지 장도 같은 규격으로 이어간다.",volumes:22},
{id:"nehemiah",path:"ot/nehemiah/index.html",title:"느헤미야 연구 서가",original:"דִּבְרֵי נְחֶמְיָה",script:"heb",meta:"표준형 서가 — 성경읽기 · 종합 개관 · 장별 심층연구 13편 · 원어 파싱 13편 · 기존 인터라이너 5편",desc:"성벽 재건에서 공동체 개혁까지 열세 장 전체를 절 단위로 주해했다. 책별 서가에서 성경읽기, 종합 개관, 장별 심층연구와 원어 연구를 연결한다.",volumes:14},
{id:"esther",path:"ot/esther/index.html",title:"에스더 연구 서가",original:"אֶסְתֵּר",script:"heb",meta:"종합 개관 1편 · 장별 심층연구 10편 · Macchi·Grossman·Llewellyn-Jones·Carruthers·Bechtel 종합 · 개역개정 대조",desc:"하나님의 이름 없이 하나님의 일을 이야기하는 책. 세 본문과 편집 과정, 페르시아 궁정 배경, 열 잔치와 교차구조, 수용사를 조망하고 열 장 전체를 절 단위로 주해한다.",volumes:11},
{id:"psalms",path:"ot/psalms/index.html",title:"시편 상세 연구",original:"תְּהִלִּים",script:"heb",meta:"예외형 — 전체 개관 1편 · 자료집 1편 · 권별 상세 연구 5편 · 시편 1–150편",desc:"시편은 150편을 다섯 권의 정경 구조로 읽는 예외형 연구 세트다. 전체 개관과 자료집, 다섯 권의 상세 연구 구조를 유지한다.",volumes:7},
{id:"hosea",path:"ot/hosea/index.html",title:"호세아서 연구 노트",original:"הוֹשֵׁעַ",script:"heb",meta:"예외형 — 일곱 주석 종합 · 배경 연구 · 14장 절 단위 주해 · 신학 · 상호 참조 · 복음적 해석",desc:"고멜과의 혼인 서사에서 심판과 소생까지 열네 장을 통합 연구 노트로 구성했다. 별도 지시가 있기 전까지 현재 구조를 유지한다.",volumes:7},
{id:"joel",path:"ot/joel/index.html",title:"요엘 연구 서가",original:"יוֹאֵל",script:"heb",meta:"표준형 서가 — 성경읽기 · 종합 개관 1편 · 장별 심층연구 3편 · 원어 연구 준비 중",desc:"메뚜기 재앙에서 여호와의 날, 회개, 영의 부어짐, 열방 심판까지 세 장을 절 단위로 주해했다. 책별 서가에서 성경읽기, 종합 개관과 장별 심층연구를 연결한다.",volumes:4},
{id:"haggai",path:"ot/haggai/index.html",title:"학개 연구 서가",original:"חַגַּי",script:"heb",meta:"표준형 서가 — 성경읽기 · 종합 개관 1편 · 장별 심층연구 2편 · 원어 연구 1:1–4 표본",desc:"넉 달 동안 선포된 네 신탁을 성경읽기, 종합 개관, 두 장의 심층연구와 파싱·인터라이너 융합 원어 연구 표본으로 연결한다.",volumes:4}]},
{id:"nt",label:"신약 연구",original:"Καινὴ Διαθήκη",script:"grk",studies:[{id:"acts",path:"nt/acts/index.html",title:"사도행전 연구 서가",original:"ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ",script:"grk",meta:"표준형 서가 — 성경읽기 · 종합 개관 1편 · 장별 심층연구 10편 완성(28장 예정) · 원어 연구 준비 중",desc:"오순절 성령 강림에서 로마의 셋집까지, 한 증언이 예루살렘에서 땅 끝으로 나아간다. Bruce(NICNT)·Peterson(PNTC)·Schnabel(ZECNT) 세 주석을 절 범위 단위로 종합하고 개역개정 4판과 NA28로 대조한다. 종합 개관과 1–10장 심층연구를 완성했고 11–28장을 같은 규격으로 이어간다.",volumes:6},{id:"romans",path:"nt/romans/index.html",title:"로마서 연구 서가",original:"ΠΡΟΣ ΡΩΜΑΙΟΥΣ",script:"grk",meta:"표준형 서가 — 성경읽기 · 종합 개관 · 장별 심층연구 1–16장 · A–E 보완 · 원어 연구 미구현",desc:"열여섯 장 전체의 심층연구에 자료 칩 정합화, 바르트 독법 보강, 로마서 13장 수용사, 누락 장의 주석별 독법, 12–16장 해설 박스를 추가했다. 직접 확인 일곱 종과 재인용 두 종을 구분한다.",volumes:17}]},
{id:"theology",label:"신학 연구",original:"Θεολογία",script:"grk",studies:[{id:"reformed",path:"https://gyu1718.github.io/Reformed_Theology_Research_Archive/",title:"개혁신학 연구 아카이브",original:"Reformata Semper Reformanda",script:"lat",meta:"개혁파 정통 ⇄ 바르트 신정통 대조 — 4대 조직신학 · 신조 모음 · 인물 · 신학사 · 주제 대조",desc:"개혁파 정통과 칼 바르트의 신정통주의를 나란히 읽는 교육 아카이브. 네 권의 조직신학을 장·절 단위로 펼치고, 신앙고백서와 신학사, 인물·주제 대조를 데이터로 엮었다.",volumes:4}]}]};
(function(){if(typeof document==="undefined")return;if(!document.querySelector("link[data-home-compact-css]")){var l=document.createElement("link");l.rel="stylesheet";l.href="assets/css/home-compact.css";l.dataset.homeCompactCss="";document.head.appendChild(l)}})();
(function(){if(typeof document==="undefined"||document.querySelector("script[data-rd-loader]"))return;var c=document.currentScript,s=c&&c.src?new URL("assets/js/research-dock-loader.js?v=20260726.1",c.src).href:"assets/js/research-dock-loader.js?v=20260726.1",n=document.createElement("script");n.src=s;n.dataset.rdLoader="";document.head.appendChild(n)})();
