(function(){
"use strict";
var data={
1:["승천과 맛디아","μάρτυρες","부활 후 사십 일, 이스라엘 회복의 물음, 증인 파송, 승천과 맛디아 선출."],2:["오순절","Πεντηκοστή","성령 강림과 베드로의 설교, 회개와 세례, 첫 공동체의 삶."],3:["미문의 표적","ὡραία","못 걷는 이의 치유, 예수 이름의 능력, 만물의 회복과 언약."],4:["첫 심문","παρρησία","사도들의 체포와 공회 심문, 다른 이름 없는 구원과 공동체의 담대함."],5:["아나니아와 삽비라","φόβος μέγας","공동체 안의 거짓과 심판, 사도들의 표적과 두 번째 공회 충돌."],6:["일곱을 세움","διακονία","구제 갈등과 일곱 사람의 선출, 스데반을 통해 이어지는 말씀의 확장."],7:["스데반의 변론","σκληροτράχηλοι","이스라엘 역사를 다시 읽는 스데반의 변론과 순교."],8:["흩어짐과 확장","εὐαγγελίζεσθαι","박해로 흩어진 이들이 사마리아와 광야 길에 복음을 전한다."],9:["사울의 회심","σκεῦος ἐκλογῆς","다메섹 도상의 부르심과 아나니아, 사울의 첫 증언."],10:["고넬료","οὐκ ἔστιν προσωπολήμπτης","베드로의 환상과 고넬료의 집, 이방인에게 임한 성령."],11:["안디옥 교회","Χριστιανούς","이방인의 회개 보고, 안디옥 교회의 성장과 처음 불린 그리스도인."],12:["헤롯과 베드로","ὁ λόγος ηὔξανεν","야고보의 순교, 베드로의 구출, 헤롯의 죽음과 말씀의 흥왕."],13:["1차 여행 개시","ἀφορίσατε δή μοι","성령의 파송, 구브로와 비시디아 안디옥, 이방의 빛으로 향하는 복음."],14:["이고니온과 루스드라","θύραν πίστεως","표적과 박해, 루스드라의 돌맞음, 장로 임명과 믿음의 문."],15:["예루살렘 공회","χάριτι κυρίου Ἰησοῦ","할례 논쟁과 은혜로 얻는 구원, 이방 교회에 보낸 공회의 편지."],16:["유럽 진입","διαβὰς εἰς Μακεδονίαν","성령의 인도, 루디아와 점치는 여종, 빌립보 간수에게 이른 복음."],17:["아레오바고","ἀγνώστῳ θεῷ","데살로니가와 베뢰아를 지나 아덴의 철학자들에게 선포된 창조주와 부활."],18:["고린도와 갈리오","οὐδεὶς ἐπιθήσεταί σοι","아굴라와 브리스길라, 고린도 사역, 갈리오의 판결과 아볼로."],19:["에베소","οὕτως κατὰ κράτος","두란노 서원, 에베소의 표적과 마술책 소각, 아데미 소동."],20:["밀레도 고별","προσέχετε ἑαυτοῖς","드로아의 유두고와 에베소 장로들을 향한 바울의 마지막 권면."],21:["체포","τὸ θέλημα τοῦ κυρίου","결박의 예고, 예루살렘 도착과 성전 체포."],22:["층대의 변론","ἀκούσατέ μου τῆς ἀπολογίας","히브리 말로 전한 회심 증언과 로마 시민권의 확인."],23:["공회와 음모","καὶ εἰς Ῥώμην","공회 분열, 로마 증언의 약속, 암살 음모와 가이사랴 이송."],24:["벨릭스 앞에서","περὶ δικαιοσύνης","더둘로의 고발과 바울의 변론, 의와 절제와 심판에 대한 대화."],25:["베스도와 상소","Καίσαρα ἐπικαλοῦμαι","새 총독 베스도 앞의 재판과 가이사 상소, 아그립바의 방문."],26:["아그립바 앞에서","ὑπηρέτην καὶ μάρτυρα","세 번째 회심 증언과 선지자들의 소망, 왕 앞에서 선포된 부활."],27:["항해와 파선","οὕτως γενήσεται","유라굴로 광풍 속의 약속과 용기, 멜리데 앞 파선과 전원 구조."],28:["로마","μετὰ πάσης παρρησίας","멜리데의 치유와 로마 도착, 매이지 않은 하나님 나라의 선포."]};
var chapters=Object.keys(data).map(Number);
var pad=function(n){return String(n).padStart(2,"0")};
var meta=document.querySelector('meta[name="description"]');if(meta)meta.content="사도행전 28장 성경읽기와 종합 개관, 1–28장 전체 심층연구를 검색·필터·최근 읽기 기능으로 연결하는 사도행전 연구 서가.";
var badge=document.querySelector('.book-path.study .book-badge');if(badge){badge.textContent="1–28장 전체 완성";badge.classList.remove("partial")}
var study=document.querySelector('.book-path.study p');if(study)study.textContent="스물여덟 장 전체를 단락 구조, 절 범위 주해, 주석별 독법, 쟁점, 상호 참조와 장별 신학 종합으로 연결한다.";
var latest=document.getElementById("latest-update");if(latest){var head=latest.querySelector(".book-shelf-head");if(head)head.innerHTML='<div class="book-shelf-eyebrow">LATEST UPDATE</div><h2>예루살렘에서 로마까지 — 전 28장 완성</h2><p>16–28장까지의 선교 여행, 체포와 변론, 로마 상소, 항해와 파선, 로마의 담대한 하나님 나라 선포를 모두 연결했다.</p>';var actions=latest.querySelector(".book-actions");if(actions){actions.innerHTML="";for(var k=16;k<=28;k++){var la=document.createElement("a");la.href="ch"+pad(k)+".html";la.textContent=k+"장 "+data[k][0];actions.appendChild(la)}}}
var shelf=document.querySelector(".book-shelf");if(shelf){chapters.forEach(function(n){var num=[].slice.call(shelf.querySelectorAll(".num")).find(function(x){return parseInt(x.textContent,10)===n});if(!num)return;var old=num.closest(".book-spine");if(!old||old.tagName==="A")return;var a=document.createElement("a");a.className=old.className.replace(/\bpending\b/g,"").trim();a.href="ch"+pad(n)+".html";while(old.firstChild)a.appendChild(old.firstChild);old.replaceWith(a)})}
document.querySelectorAll(".book-shelf-note").forEach(function(n){if(/종합 개관|장별 심층연구|16–28장/.test(n.textContent))n.textContent="종합 개관 1편 완성 · 장별 심층연구 28/28편 완성 · 원어 연구 준비 중"});
var section=document.getElementById("chapters"),list=section&&section.querySelector(".book-chapter-list");if(!list)return;
var statusText=section.querySelector(".book-shelf-head p");if(statusText)statusText.textContent="성경읽기와 장별 심층연구가 스물여덟 장 모두 활성화되어 있다.";
function rowFor(n){var d=data[n],article=document.createElement("article");article.className="book-chapter-row";article.dataset.status="complete";article.innerHTML='<span class="no">'+pad(n)+'</span><span class="original">'+d[1]+'</span><span><h3>'+d[0]+'</h3><p>'+d[2]+'</p></span><span class="book-actions"><a href="../../bible/original.html?book=ACT&amp;chapter='+n+'">성경읽기</a><a href="ch'+pad(n)+'.html">심층연구</a><span aria-disabled="true" class="disabled" role="note">원어연구 준비 중</span></span>';return article}
var existing={};[].slice.call(list.querySelectorAll(".book-chapter-row")).forEach(function(r){var no=parseInt((r.querySelector(".no")||{}).textContent||"0",10);if(!no)return;existing[no]=r;r.dataset.status="complete";var actions=r.querySelector(".book-actions");if(actions&&!actions.querySelector('a[href="ch'+pad(no)+'.html"]')){var pending=[].slice.call(actions.querySelectorAll(".disabled")).find(function(x){return /심층연구/.test(x.textContent)});if(pending){var a=document.createElement("a");a.href="ch"+pad(no)+".html";a.textContent="심층연구";pending.replaceWith(a)}}});
chapters.forEach(function(n){if(!existing[n])list.appendChild(rowFor(n))});
var tools=document.getElementById("actsShelfTools");if(!tools){tools=document.createElement("div");tools.id="actsShelfTools";tools.className="chapter-tools";tools.setAttribute("role","search");tools.innerHTML='<label for="actsChapterSearch">장 번호 또는 제목 검색</label><input id="actsChapterSearch" type="search" placeholder="예: 17, 아레오바고, 로마, 성령" autocomplete="off"><div class="chapter-filters" aria-label="연구 상태 필터"><button type="button" data-status="all" aria-pressed="true">전체</button><button type="button" data-status="complete" aria-pressed="false">완성</button><button type="button" data-status="pending" aria-pressed="false">준비 중</button></div><div class="chapter-result" id="actsResult" aria-live="polite">28개 장 표시</div>';list.parentNode.insertBefore(tools,list)}
var recent=document.getElementById("actsRecent");if(!recent){recent=document.createElement("div");recent.id="actsRecent";recent.className="book-shelf-note";recent.hidden=true;recent.innerHTML='최근 읽은 장: <a href="ch01.html">1장</a>';tools.parentNode.insertBefore(recent,tools)}
var input=document.getElementById("actsChapterSearch"),rows=[].slice.call(list.querySelectorAll(".book-chapter-row")),buttons=[].slice.call(tools.querySelectorAll(".chapter-filters button")),mode="all";
function norm(s){return String(s||"").toLowerCase().replace(/\s+/g,"")}
function apply(){var q=norm(input&&input.value),shown=0;rows.forEach(function(r){var ok=(mode==="all"||r.dataset.status===mode)&&(!q||norm(r.textContent).indexOf(q)>=0);r.hidden=!ok;if(ok)shown++});var out=document.getElementById("actsResult");if(out)out.textContent=shown+"개 장 표시"}
if(input)input.addEventListener("input",apply);buttons.forEach(function(b){b.addEventListener("click",function(){mode=b.dataset.status;buttons.forEach(function(x){x.setAttribute("aria-pressed",x===b?"true":"false")});apply()})});apply();
try{var n=parseInt(localStorage.getItem("acts-recent-chapter")||"0",10);if(data[n]){var link=recent.querySelector("a");link.href="ch"+pad(n)+".html";link.textContent=n+"장 · "+data[n][0];recent.hidden=false}}catch(e){}
var foot=document.querySelector("footer");if(foot)foot.innerHTML=foot.innerHTML.replace(/장별 심층연구\s*\d+(?:\/28)?편/g,"장별 심층연구 28/28편").replace(/1–15장|1–17장 및 25–28장/g,"1–28장");
})();
